apiVersion: v1
kind: Secret
metadata:
  name: django-secret
type: Opaque
data:
  POSTGRES_PASSWORD: ZGphbmdvX3Bhc3N3b3Jk
  RABBITMQ_DEFAULT_USER: cm9vdA==
  RABBITMQ_DEFAULT_PASS: cm9vdA==
  DJANGO_SECRET_KEY: ZGphbmdvLWluc2VjdXJlLXAyITRqMnEyYWleKXlqNGs4JmZwMjI0biloamw9Xig5aXMyPWIkK2YjY2YjKzJ2NjR1